services:

  jsf:
    build: .
    ports:
      - '8080:8080'

  db:
    container_name: db
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=lab3db'
      - 'POSTGRES_PASSWORD=postgres'
